;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-delete-region
        ))

(setq mc/cmds-to-run-once
      '(
        dabbrev-expand
        mouse-minor-mode-menu
        mouse-select-window
        yas-expand
        ))
